train_model --label_dir /home/noah/data/FETAL_PLANES_ZENODO/FETAL_PLANES_DB_data.csv \
               --data_dir /home/noah/data/FETAL_PLANES_ZENODO/Images \
               --data_name FetalPlanes \
               --model DenseNet169 \
               --train_strategy train_classification \
               --use_scheduler True \
               --batch_size 32 \
               --num_epochs  1 \
               --optimizer SGD \
               --lr 0.0002 \
               --momentum 0.9